@BookStore.Api_HostAddress = http://localhost:5079
@id = ea6cca86-406b-4e2b-be20-fc0063acc411
@id2 = 0bda4394-dfab-4562-a52d-7f9131f99f58
### Create Book Feature
POST {{BookStore.Api_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Clean Architecture",
  "author": "Robert C. Martin",
  "price": 39.99,
  "publishedOn": "2017-08-02"
}

### GetBookById Feature
GET {{BookStore.Api_HostAddress}}/api/books/{{id}}
Content-Type: application/json

###

### Create Book Feature
POST {{BookStore.Api_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Modular Monolith",
  "author": "Morteza Giti",
  "price": 39.99,
  "publishedOn": "2017-08-02"
}


### Adding FluentVAlidation: Invalid book Creation request
POST {{BookStore.Api_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "",
  "author": "",
  "price": -10,
  "publishedOn": "2026-08-02"
}



### GetAllBooks Feature
GET {{BookStore.Api_HostAddress}}/api/books
Content-Type: application/json